# Generated by Django 6.0.4 on 2026-04-22 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'HSK 1'), (2, 'HSK 2'), (3, 'HSK 3'), (4, 'HSK 4')])),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('detailed_explanation', models.TextField(blank=True)),
                ('example_cn', models.TextField(blank=True)),
                ('example_pinyin', models.TextField(blank=True)),
                ('example_en', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsk_level', models.IntegerField()),
                ('chinese', models.CharField(max_length=100)),
                ('pinyin', models.CharField(max_length=100)),
                ('english', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('daily_goal', models.IntegerField(default=20)),
                ('words_studied_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('total_words_learned', models.IntegerField(default=0)),
                ('total_study_time_minutes', models.IntegerField(default=0)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('preferred_audio', models.BooleanField(default=True)),
                ('show_pinyin_on_front', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('LEARNING', 'Learning'), ('REVIEW', 'Review'), ('MASTERED', 'Mastered')], default='NEW', max_length=20)),
                ('difficulty', models.CharField(choices=[('normal', 'Normal'), ('hard', 'Hard'), ('easy', 'Easy')], default='normal', max_length=10)),
                ('consecutive_correct', models.IntegerField(default=0)),
                ('next_review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('times_reviewed', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('first_learned', models.DateTimeField(blank=True, null=True)),
                ('studied_in_session', models.BooleanField(default=False)),
                ('session_correct', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
