# Generated by Django 6.0.4 on 2026-04-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='antonyms',
            field=models.TextField(blank=True, help_text='Comma-separated list of antonyms'),
        ),
        migrations.AddField(
            model_name='word',
            name='character_breakdown',
            field=models.TextField(blank=True, help_text='Breakdown of individual characters and their meanings'),
        ),
        migrations.AddField(
            model_name='word',
            name='example_sentences',
            field=models.JSONField(blank=True, default=list, help_text='List of example sentences with pinyin and translation'),
        ),
        migrations.AddField(
            model_name='word',
            name='frequency_rank',
            field=models.IntegerField(blank=True, help_text='Frequency rank in common usage', null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='grammar_points',
            field=models.TextField(blank=True, help_text='Grammar points related to this word'),
        ),
        migrations.AddField(
            model_name='word',
            name='radical',
            field=models.CharField(blank=True, help_text='Primary radical of the character(s)', max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='stroke_count',
            field=models.IntegerField(blank=True, help_text='Total stroke count', null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.TextField(blank=True, help_text='Comma-separated list of synonyms'),
        ),
        migrations.AddField(
            model_name='word',
            name='usage_notes',
            field=models.TextField(blank=True, help_text='Detailed usage notes and context'),
        ),
    ]
