# Generated by Django 6.0.4 on 2026-04-22 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_word_antonyms_word_character_breakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hsk_level', models.IntegerField(choices=[(1, 'HSK 1'), (2, 'HSK 2'), (3, 'HSK 3'), (4, 'HSK 4'), (5, 'HSK 5'), (6, 'HSK 6')])),
                ('description', models.TextField(blank=True, help_text='Description of the book content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['hsk_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(help_text='Chapter number (e.g., 1, 2, 3)')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Brief summary of what this chapter covers')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='flashcards.book')),
            ],
            options={
                'verbose_name_plural': 'Chapters',
                'ordering': ['book', 'chapter_number'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='TextSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Order of appearance in the chapter')),
                ('chinese_text', models.TextField(help_text='Chinese characters (Simplified)')),
                ('pinyin', models.TextField(help_text='Pinyin with tone marks')),
                ('english_translation', models.TextField(help_text='English translation')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chapter_audio/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='flashcards.chapter')),
                ('key_words', models.ManyToManyField(blank=True, help_text='Key vocabulary words in this segment', to='flashcards.word')),
            ],
            options={
                'verbose_name_plural': 'Text Segments',
                'ordering': ['chapter', 'order'],
            },
        ),
    ]
